version: 2
jobs:
  build:

    docker:
      - image: circleci/node:6-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install node@6.2.2 (need right version for `yarn`)
          command: |
            set +e
            touch $BASH_ENV
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo 'nvm install v8.9' >> $BASH_ENV
            echo 'nvm alias default v8.9' >> $BASH_ENV

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn ng build --prod --build-optimizer --no-progress
      - run: yarn ng test --single-run --no-progress